name: Java CI with Maven

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    if: github.event.action != 'labeled' || contains(github.event.pull_request.labels.*.name, 'RunTests')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build and run tests with JaCoCo aggregation
        run: mvn clean verify -T 3

      - name: Display JaCoCo report (optional debug)
        run: cat coverage/target/site/jacoco-aggregate/jacoco.xml

      - name: Analyze on SonarCloud
        run: mvn sonar:sonar \
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.coverage.jacoco.xmlReportPaths=coverage/target/site/jacoco-aggregate/jacoco.xml