name: Java CI with Maven

on:
  pull_request:
    types: [labeled]

  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to analyze (must be "main")'
        required: true
        default: 'main'

jobs:
  build:
    if: >
      github.event_name == 'workflow_dispatch' && github.event.inputs.branch == 'main' ||
      github.event_name == 'pull_request' && (github.event.action != 'labeled' || contains(github.event.pull_request.labels.*.name, 'RunTests'))
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref_name }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Fetch base branch for SonarCloud PR analysis
        if: github.event_name == 'pull_request'
        run: git fetch origin ${{ github.event.pull_request.base.ref }}

      - name: Build and run tests with JaCoCo aggregation
        run: mvn clean verify -T 3

      - name: Display JaCoCo report (optional debug)
        run: |
          echo "First 20 lines of JaCoCo XML:"
          head -n 20 coverage/target/site/jacoco-aggregate/jacoco.xml || echo "File not found"

      - name: Analyze on SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            mvn sonar:sonar \
              -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
              -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
              -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} \
              -Dsonar.pullrequest.branch=${{ github.head_ref }} \
              -Dsonar.pullrequest.base=${{ github.base_ref }} \
              -Dsonar.coverage.jacoco.xmlReportPaths=coverage/target/site/jacoco-aggregate/jacoco.xml
          else
            mvn sonar:sonar \
              -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
              -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
              -Dsonar.coverage.jacoco.xmlReportPaths=coverage/target/site/jacoco-aggregate/jacoco.xml
          fi